export const FETCH_CUISINES = 'FETCH_CUISINES'
export const FETCH_RECIPE_DETAILS_INFO = 'FETCH_RECIPE_DETAILS_INFO'
export const FETCH_HERO_DATA = 'FETCH_HERO_DATA'
export const FETCH_USERS_RECIPES = 'FETCH_USERS_RECIPES'
export const FETCH_USERS_RECIPE_DETAILS_INFO = "FETCH_USERS_RECIPE_DETAILS_INFO"
