const express = require('express')
const router = express.Router()
const {check} = require('express-validator')
const recipeController = require('../controllers/mealplans')
const checkAuth = require('../middleware/check-auth')
